[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concordium-rwa-identity-registry = { path = "../identity-registry" }
concordium-rwa-compliance = { path = "../compliance" }
concordium-rwa-security-nft = { path = "../security-nft" }
concordium-rwa-market = { path = "../market" }
euroe_stablecoin = { path = "../euroe" }
concordium-std = { version = "8.1.0", default-features = false }
concordium-cis2 = { version = "5.1.0", default-features = false }
concordium-rwa-utils = { path = "../utils" }

[dev-dependencies]
concordium-smart-contract-testing = "3"

[lib]
crate-type = ["cdylib", "rlib"]